language: python 
python: 
- "3.6"
- "3.5"
services:
- postgresql
env: 
- DJANGO=2.0 DB=postgres
global:
  - PGPORT=5432
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
- pip install -U pip
- pip install -U flake8
before_script: 
- cp local_settings.example.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python manage.py makemigrations
- python manage.py migrate
script: 
- flake8 --statistics --count --ignore E501,E201,E202,E231 --max-complexity=10 --benchmark --exit-zero
- python manage.py test
addons:
    postgresql: "9.6"