language: python 
python:
- "3.6"
- "3.5"
services:
- postgresql
env:
- DJANGO=2.0 DB=postgres
global:
  - PGPORT=5432
before_install:
- cd decide
install:
- travis_wait 30 mvn install
- pip install -r ../requirements.txt
- wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
- cp local_settings.example.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python manage.py makemigrations
- python manage.py migrate
script:
- whereis google-chrome-stable
- whereis chromedriver
- python manage.py runserver
- python manage.py test
addons:
    postgresql: "9.6"
    chrome: stable
