language: python
python:
- '3.6'
- '3.5'
services:
- postgresql
env:
- DJANGO=2.0 DB=postgres
global:
- PGPORT=5432
before_install:
- cd decide
install:
- pip install -r ../requirements.txt
before_script:
- cp local_settings.example.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python manage.py makemigrations
- python manage.py migrate
- python manage.py loaddata initial_data
script:
- python manage.py test
addons:
  postgresql: '9.6'
jobs:
    include:
        - stage: deploy
          script: skip
          before_deploy:
              - cd ..
          deploy:
            provider: heroku
            api_key:
                secure: pRRamT23pAi4keCpxfxKeCUCxVqt0hNbIObvkm5Q3HbTdaqmcxw8kXDgWtIGMPBxUc9ldW3JPoIxh768j78+s0SvuUJ+XzA/o51LhXW194Kf2fzWkpGBhPN4QI4NPFcj8XogLIT4OB2jZ/2RdXnmw7F4c4i7wnxOODaHAmezalRj4zIewuxBUHTb8iyqTjhGUrdAHO6rpz1URJOTJkem2gp5ia8lDA3nJiGGA5IoFUFp93c/uKANOksHXRvW0j2KUMyuzgIOcbApLqzecgCqXlse4GlA9FqU+FXcYuNM3FDU0FQRbvlC7RXonrZbB7uOSOuZZmj1XQSmCjfXK1aTMNNJGJlaAkybeZ3GCKVFm0A979/p4SK/jnNRd8WsctkZJ6nMFyKdE8IfuPlSbCM6shkyG4n3cPm7KX5Xtdij51bEzqF3iCMfYzm++gzHv0z2usaXSGRb/GAnKryITiG/tewmc6YruqAOCUz2SYzF313i/poPwuLjpe1iihGQQaMyJ88Ufnw6+6VqWJcfdrGaNzj9sxo9vdCyXinC3MvFmXQhuv4ixSQE/V37alZjqPLMDyuIXHOwkPP7uqH+UiDfrIVGKqhiFAYAExmsRkoq7SPKV7xHM0ff7vN1YxsF1MuyiErscayJrr5a5AyM4Y/ZdVeIe0fZHjAlyZvGjGL4xHY=
            app: locaste-decide